### ISSUE TITLE
is this project abandoned???

### ISSUE THREAD

**Issue by tmzasz** [Minuit-Ferina/vscode-lsl#12]
creator seems to ignore issues since march, rather lame and not professional.

**Comment by Minuit-Ferina** [comment]
Hi 

I'm sorry to hear that you are not satisfied with the support I offered. Unfortunately, I wasn't able to reproduce your issue.

While I strive to offer support and maintain this project as a free resource, please understand that this project is maintained on a voluntary basis, and I am not paid for my contributions. My capacity to provide support or to work on this project is limited due to my other commitments. This project has already required several hundred hours of unpaid work.

For urgent or specialized assistance, you might consider hiring a professional who can dedicate the necessary time and resources to your specific needs.

Thank you for understanding.

Best regards
